# Generated by Django 4.1.3 on 2022-12-19 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0010_alter_appuser_cv_alter_appuser_qr_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('returns', models.FloatField(default=0)),
                ('amount_tax', models.FloatField(default=0)),
                ('returns_tax', models.FloatField(default=0)),
                ('total_tax', models.FloatField(default=0)),
                ('payment_hash', models.CharField(default='none', max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_confirmation_status', models.BooleanField(default=False)),
                ('request_payment_status', models.BooleanField(default=False)),
                ('closed_status', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
    ]
