# Generated by Django 4.1.3 on 2022-12-12 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0007_alter_appuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('answer_a', models.CharField(default='None', max_length=50)),
                ('answer_b', models.CharField(default='None', max_length=50)),
                ('answer_c', models.CharField(default='None', max_length=50)),
                ('answer_d', models.CharField(default='None', max_length=50)),
                ('answer', models.CharField(default='None', max_length=50)),
                ('category', models.CharField(default='general', max_length=50)),
                ('level', models.CharField(default='simple', max_length=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=50)),
                ('detail', models.TextField(default='none')),
                ('duration', models.CharField(default='none', max_length=50)),
                ('question_no', models.IntegerField(default=1)),
                ('barrier', models.IntegerField(default=50)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.CharField(default='none', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQandAConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.qanda')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='QandAs',
            field=models.ManyToManyField(through='quiz.QuizQandAConnector', to='quiz.qanda'),
        ),
    ]
