# Generated by Django 4.1.3 on 2022-11-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_appuser_city_appuser_current_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='state',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='appuser',
            name='job_category',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='language',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='postcode',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
