# Generated by Django 4.1.3 on 2022-11-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_rename_state_appuser_experience_appuser_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.TextField(default='This agency have not updated their bio..', null=True),
        ),
    ]
