# Generated by Django 4.1.3 on 2022-12-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_alter_appuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.CharField(default='dd/mm/yyyy', max_length=55),
        ),
    ]
