# Generated by Django 4.1.3 on 2022-12-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_alter_appuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='cv',
            field=models.FileField(blank=True, default='https://aibra.io/static/main/assets/img/fav.png', upload_to='account_files/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.FileField(blank=True, default='https://aibra.io/static/main/assets/img/fav.png', upload_to='account_files/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='qr_photo',
            field=models.FileField(blank=True, default='https://aibra.io/static/main/assets/img/fav.png', upload_to='account_files/profile_photos/'),
        ),
    ]
