# Generated by Django 4.1.3 on 2022-12-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0011_alter_appuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.FileField(blank=True, default='default_files/default_face.jpg', upload_to='account_files/profile_photos/'),
        ),
    ]
