# Generated by Django 4.1.3 on 2022-11-23 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(default='none', max_length=50)),
                ('detail', models.TextField(default='none')),
                ('year', models.CharField(default='none', max_length=50)),
                ('link', models.CharField(default='#', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.TextField(default='none')),
                ('detail', models.TextField(default='none')),
                ('date_from', models.CharField(default='none', max_length=50)),
                ('date_to', models.CharField(default='none', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(default='none', max_length=50)),
                ('detail', models.TextField(default='none')),
                ('year', models.CharField(default='none', max_length=50)),
                ('link', models.CharField(default='#', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(default='none', max_length=50)),
                ('detail', models.TextField(default='none')),
                ('date_from', models.CharField(default='none', max_length=50)),
                ('date_to', models.CharField(default='none', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(default='none', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Involvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=50)),
                ('detail', models.TextField(default='none')),
                ('link', models.CharField(default='#', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_statement', models.TextField(default='none')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='none', max_length=50)),
                ('detail', models.TextField(default='none')),
                ('link', models.CharField(default='#', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.CharField(default='none', max_length=50)),
                ('phone_no', models.CharField(default='none', max_length=50)),
                ('email', models.CharField(default='none', max_length=50)),
                ('place_of_work', models.TextField(default='none', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_tag', models.CharField(default='resume x', max_length=20)),
                ('resume_cent', models.IntegerField(default=0)),
                ('resume_status', models.BooleanField(default=False)),
                ('work_experience_status', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='none', max_length=50)),
                ('detail', models.TextField(default='none')),
                ('date_from', models.CharField(default='none', max_length=50)),
                ('date_to', models.CharField(default='none', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience', models.CharField(default='none', max_length=50)),
                ('company', models.CharField(default='none', max_length=50)),
                ('detail', models.TextField(default='none')),
                ('date_from', models.CharField(default='none', max_length=50)),
                ('date_to', models.CharField(default='none', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeWorkExperienceConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.workexperience')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTitleConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.title')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSkillConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeRefereeConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.referee')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeProjectConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.project')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeOpeningStatementConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.openingstatement')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeInvolvementConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('involvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.involvement')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeHobbyConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.hobby')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEducationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.education')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCertificationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.certification')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCareerConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.career')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAwardConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.award')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='awards',
            field=models.ManyToManyField(through='resume.ResumeAwardConnector', to='resume.award'),
        ),
        migrations.AddField(
            model_name='resume',
            name='careers',
            field=models.ManyToManyField(through='resume.ResumeCareerConnector', to='resume.career'),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.ManyToManyField(through='resume.ResumeCertificationConnector', to='resume.certification'),
        ),
        migrations.AddField(
            model_name='resume',
            name='educations',
            field=models.ManyToManyField(through='resume.ResumeEducationConnector', to='resume.education'),
        ),
        migrations.AddField(
            model_name='resume',
            name='hobbies',
            field=models.ManyToManyField(through='resume.ResumeHobbyConnector', to='resume.hobby'),
        ),
        migrations.AddField(
            model_name='resume',
            name='involvements',
            field=models.ManyToManyField(through='resume.ResumeInvolvementConnector', to='resume.involvement'),
        ),
        migrations.AddField(
            model_name='resume',
            name='opening_statements',
            field=models.ManyToManyField(through='resume.ResumeOpeningStatementConnector', to='resume.openingstatement'),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.ManyToManyField(through='resume.ResumeProjectConnector', to='resume.project'),
        ),
        migrations.AddField(
            model_name='resume',
            name='referees',
            field=models.ManyToManyField(through='resume.ResumeRefereeConnector', to='resume.referee'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(through='resume.ResumeSkillConnector', to='resume.skill'),
        ),
        migrations.AddField(
            model_name='resume',
            name='titles',
            field=models.ManyToManyField(through='resume.ResumeTitleConnector', to='resume.title'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experiences',
            field=models.ManyToManyField(through='resume.ResumeWorkExperienceConnector', to='resume.workexperience'),
        ),
    ]
