# Generated by Django 4.1.3 on 2022-12-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='detail',
            new_name='course',
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
