# Generated by Django 4.1.3 on 2022-12-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_keyskill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeySkill',
        ),
    ]
