# Generated by Django 4.1.3 on 2022-12-12 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(default='None', max_length=50)),
                ('answer', models.CharField(default='None', max_length=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAnswerConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=50)),
                ('salary', models.CharField(default='none', max_length=30)),
                ('category', models.CharField(default='none', max_length=30)),
                ('description', models.TextField(default='none')),
                ('job_type', models.CharField(default='none', max_length=20)),
                ('responsibility', models.TextField(default='none')),
                ('requirement', models.TextField(default='none')),
                ('contact_phone', models.CharField(default='none', max_length=20)),
                ('contact_email', models.CharField(default='none', max_length=30)),
                ('address', models.TextField(default='none')),
                ('country', models.CharField(default='none', max_length=30)),
                ('deadline', models.CharField(default='none', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobInterviewConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter', models.CharField(default='none', max_length=50)),
                ('title', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(default='none')),
                ('salary', models.CharField(default='none', max_length=30)),
                ('job_type', models.CharField(default='none', max_length=30)),
                ('slots', models.CharField(default='none', max_length=20)),
                ('deadline', models.CharField(default='none', max_length=30)),
                ('job_id', models.CharField(default='none', max_length=30)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobResultConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
