# Generated by Django 4.1.3 on 2022-12-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('app_user', '0007_alter_appuser_age'),
        ('job', '0001_initial'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresultconnector',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.result'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser'),
        ),
        migrations.AddField(
            model_name='jobinterviewconnector',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview'),
        ),
        migrations.AddField(
            model_name='jobinterviewconnector',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
        migrations.AddField(
            model_name='jobapplicationconnector',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application'),
        ),
        migrations.AddField(
            model_name='jobapplicationconnector',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser'),
        ),
        migrations.AddField(
            model_name='job',
            name='applications',
            field=models.ManyToManyField(through='job.JobApplicationConnector', to='job.application'),
        ),
        migrations.AddField(
            model_name='job',
            name='interviews',
            field=models.ManyToManyField(through='job.JobInterviewConnector', to='interview.interview'),
        ),
        migrations.AddField(
            model_name='job',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='job',
            name='results',
            field=models.ManyToManyField(through='job.JobResultConnector', to='quiz.result'),
        ),
        migrations.AddField(
            model_name='applicationanswerconnector',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.answer'),
        ),
        migrations.AddField(
            model_name='applicationanswerconnector',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application'),
        ),
        migrations.AddField(
            model_name='application',
            name='answers',
            field=models.ManyToManyField(through='job.ApplicationAnswerConnector', to='job.answer'),
        ),
        migrations.AddField(
            model_name='application',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser'),
        ),
        migrations.AddField(
            model_name='answer',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser'),
        ),
    ]
