# Generated by Django 4.1.3 on 2022-12-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='none', max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
