# Generated by Django 4.1.3 on 2022-12-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_experience_job_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='qualification',
        ),
    ]
