# Generated by Django 4.1.3 on 2022-12-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill_tag',
            field=models.CharField(default='no skill required', max_length=2000, null=True),
        ),
    ]
