# Generated by Django 4.1.3 on 2022-12-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_website_jobrequest_address_jobrequest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill_tag',
            field=models.CharField(default='no skill required', max_length=2000, null=True),
        ),
    ]
